### ISSUE TITLE
"No module named scipy" and so on...

### ISSUE THREAD

**Issue by tuji-sjp** [rishabh30/Facial-Expression-Recognition#1]
![111](https://user-images.githubusercontent.com/30012354/37555907-d85edef2-2a29-11e8-961e-ed68cd72d2ee.png)

What should I do?

**Comment by rishabhjainps** [comment]
Scikit-learn (Sklearn) requires:  SciPy (>= 0.13.3) 
Simply install SciPy from [https://www.scipy.org/install.html](https://www.scipy.org/install.html)

**Comment by tuji-sjp** [comment]
But there are new problems.
![111](https://user-images.githubusercontent.com/30012354/37566607-6fae9a64-2af6-11e8-8efd-e75e85ca6e76.png)

**Comment by rishabhjainps** [comment]
Problem seem to be in installation of Sklearn , Scipy. Similar problem links-[link](https://stackoverflow.com/questions/14629818/importerror-dll-load-failed-1-is-not-a-valid-win32-application) [link](https://github.com/scikit-learn/scikit-learn/issues/1180) [link](https://stackoverflow.com/questions/26638621/importerror-dll-load-failed-1-is-not-a-valid-win32-application-for-python-mat).
Also can try re-installing compatible version of Sklearn ,Scipy.

**Comment by tuji-sjp** [comment]
Ok, I'll try again. Thank you very much!
