### ISSUE TITLE
question on saved model weights

### ISSUE THREAD

**Issue by priyaganaboor** [rishabh30/Facial-Expression-Recognition#4]
The readme file says the usage of 32 (3x3) first conv2D and 2nd layer 64 (3x3), but python program cnn_major.py it is given as shown below,
    # 1 - Convolution
    model.add(Conv2D(64,(3,3), border_mode='same', input_shape=(48, 48,1)))
   # 2nd Convolution layer
    model.add(Conv2D(128,(5,5), border_mode='same'))

So, to save the model weights results which is correctly used from the above.

**Comment by priyaganaboor** [comment]
@rishabhjainps can u please reply

**Comment by rishabhjainps** [comment]
@priyaganaboor Yes you are correct.

ReadMe needs to be updated for shallow cnn, It should be 
```

First convolutional layer, we had 64 3×3 filters, along with batch normalization and dropout and max-pooling with a filter size 2×2.

Second convolutional layer, we had 128 5×5 filters, along with batch normalization and dropout and max-pooling with a filter size 2×2.
```

https://github.com/rishabhjainps/Facial-Expression-Recognition/blob/master/cnn_major_shallow.py#L70

**Comment by priyaganaboor** [comment]
Thank u so much for the reply :)

And also u said dataset is divided into 80:10:10
But I don't see that in your code.
If it is 80:10:10 ideally the images should be divided into 28,709(training), 3,589(validation), and 3,589(test).
But ur code divides the dataset into some other ratio that it results in 32298(training), 3,589(testing).

Correct right?? 
@rishabhjainps

**Comment by rishabhjainps** [comment]
Basically we first takeout 10% of whole data set as test data set. It is part which is totally untouched till the end, only used to calculate accuracy of model.

Validation dataset is there to fine tune the model hyper-parameters for CNN which is specified in below line.
https://github.com/rishabhjainps/Facial-Expression-Recognition/blob/master/cnn_major.py#L143

**Comment by priyaganaboor** [comment]
If we have to find the accuracy of individual class?
@rishabhjainps
